---
permalink: /guides/dev-getting-started-short
---
:projectid: dev-getting-started
:page-layout: guide
:page-duration: 15 minutes
:page-description: Short workshop content for developers getting started with Kabanero
:page-tags: ['Appsody', 'Nodejs', 'Express']
:page-title: Getting Started With Kabanero Development
:linkattrs:

:kabanero-collection: v0.2.0-beta1


= Getting Started With Kabanero Development

== What is Kabanero

Kabanero is an open source project focused on bringing together key
foundational open source technologies into a framework for developing
and deploying modern cloud-native applications. The Kabanero developer
experience leverages multiple open source
projects enabling developers to use project 'templates' to rapidly
create new cloud-native applications, develop and build them in a
curated container 'stack' environment and deploy them to
Knative/Kubernetes all without the need for container or Kubernetes
skills.

== What you will learn

This tutorial will give you an introduction to the Kabanero developer
experience. You’ll create and deploy a Node.js cloud-native application, 
however, Kabanero provides a number of stacks,
including Java and Spring Boot, and is extensible so others can easily
be added. For more information, see https://appsody.dev/[Appsody.dev].

At the end of this tutorial, you should have a good understanding of the
Kabanero developer experience through the use of Appsody. 

You’ll know how to create a new application, develop and
deploy it to Knative, and have an appreciation for how Kabanero does all
the heavy-lifting, helping you focus on the task of writing the code.

include::prerequisites.adoc[]

include::appsody.adoc[]
